// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Comming: typeof import('./src/components/views/Comming.vue')['default']
    Foods: typeof import('./src/components/views/content/Foods.vue')['default']
    FoodSearch: typeof import('./src/components/views/SearchContent/FoodSearch.vue')['default']
    Map: typeof import('./src/components/views/content/Map.vue')['default']
    MapSearch: typeof import('./src/components/views/SearchContent/MapSearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/views/Search.vue')['default']
    ShowMap: typeof import('./src/components/views/ShowMap.vue')['default']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
